# Generated by Django 4.1.2 on 2022-11-01 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_item_label_category_alter_item_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
